🎨 Reorganize the components and theme creation API
BattleCh1cken/notebookinator pull request #45
Opened 2024-05-21 02:35 UTC by BattleCh1cken

#### Summary

Closes #44 and #28.

#### Checklist

- [ ] I have fully tested all of the added features
- [ ] I have fully documented all of the relevant code

#### Additional Notes

2024-05-23 19:01 UTC, BattleCh1cken commented
Currently the documentation is still incomplete but I'm opening this up for review because I'm interested to know what you guys think.

2024-05-23 21:55 UTC, BestUsernamEver commented on internals.typ
what happened here?

2024-05-24 22:44 UTC, BestUsernamEver submitted a review, later dismissed
Good job, maybe we can put the new formatting into the `CONTRIBUTING.md` file unless there is a vscode extension for it or something.

2024-05-27 00:49 UTC, BestUsernamEver requested changes

2024-05-27 00:49 UTC, BestUsernamEver commented on docs/src/developer_documentation/custom_themes.md
> +Using the constructor gives us access to three variables, `frontmatter`, `body`, and `appendix`. These variables are all [arrays](https://typst.app/docs/reference/foundations/array/), which dictionar
I think there's a grammar error in the second sentence after the link?

"which dictionaries which all contain..." unless I'm reading it wrong

2024-05-27 00:49 UTC, BestUsernamEver commented on docs/src/developer_documentation/custom_themes.md
> +#let toc = utils.make-toc((_, body, appendix) => {
I think you should still include the `// replace frontmatter with _ to indicate we aren't using it` comment

2024-05-27 00:49 UTC, BestUsernamEver commented on docs/src/reference.typ
> +  All of the examples show the default theme, other theme's components will look differently.
Should be other themes' components or other theme components

2024-05-27 00:49 UTC, BestUsernamEver commented on themes/default/components.typ
> +/// #create-body-entry(title: "Table Of Contents")[
Why is this now a body entry?

2024-05-27 00:49 UTC, BestUsernamEver commented on themes/default/components.typ
> +// TODO: implementations for
I think these are personal todo comments, not doc todo comments

2024-06-02 12:51 UTC, aji-ajani commented on justfile
> +  set -euxo pipefail
What's the purpose of the just installer if the current installation options are a container and the package script?

2024-06-02 12:51 UTC, aji-ajani commented on lib.typ
>    show: doc => rules(doc)
Where does the doc parameter come from?

2024-06-02 12:51 UTC, aji-ajani commented on lib.typ
> +    margin: 0pt,
What happens if a person wants to put content in the margin of a cover?

2024-06-02 12:51 UTC, aji-ajani commented on utils/components.typ
> +      ctx.page-number = page-number
Why is it necessary to update the page number context?

2024-06-02 12:51 UTC, aji-ajani commented on utils/components.typ
> +///   // ...
No example for usage of a decision matrix constructor?

2024-06-02 12:51 UTC, aji-ajani commented on utils/components.typ
> +          message: "Property should be of type 'str'",
What case would cause this assert to fail?

2024-06-02 12:51 UTC, aji-ajani commented on utils/components.typ
> +///   Valid types include:
My team also has admonitions for design process steps. Would it be possible to add support for this per theme?

2024-06-02 12:51 UTC, aji-ajani commented on utils/components.typ
> +      panic("Entry type '" + str(type) + "' Valid types include:" + valid-types-printable)
```suggestion
      panic("Entry type '" + str(type) + "' is not valid. Valid types include:" + valid-types-printable)
```

2024-06-02 12:51 UTC, aji-ajani commented on utils/components.typ
> +/// - callback (function): A function that returns the content for the pie chart. The function must take a `data` argument.
I don't see the value of a standardized constructor for pie charts if the only common parameter is "data".

2024-06-02 12:51 UTC, aji-ajani commented on utils/components.typ
> +// TODO: add method for these extra components:
Aren't pie chart, plot, and admonition already added? Also, does "team" refer to the "Meet the Team" section at the beginning of most notebooks?

2024-06-02 12:51 UTC, aji-ajani commented on utils/theme.typ
> +  return doc => {
What information is the "doc" parameter holding?

2024-06-02 12:51 UTC, aji-ajani commented on utils/theme.typ
> +  callback,
Little nitpicky, but why does the callback parameter for this function get a new line while for the other functions in this file it doesn't get a new line?

2024-06-02 12:51 UTC, aji-ajani commented on utils/theme.typ
> +    let valid-entry-types = (
Is it going to be possible to add other entry types?

2024-06-02 12:51 UTC, aji-ajani commented on utils/theme.typ
> +        "author", // TODO: decide on the standard process for entry attribution
We could make it so that the author and witness parameters take in information as either a string or an array of strings. This way if someone wants to just have a "participants" field, they can pass in an array of names into the "author" parameter and rename the "author" field to "participants" in their theme.

2024-06-02 12:51 UTC, aji-ajani commented on utils/theme.typ
> +      panic("Entry type '" + str(ctx.type) + "' Valid types include:" + valid-types-printable)
Clarity improvement.

```suggestion
      panic("Entry type '" + str(ctx.type) + "' is not valid. Valid types include:" + valid-types-printable)
```

2024-06-02 12:51 UTC, aji-ajani commented on utils/theme.typ
> +// All of the check logic is exactly the same, so we can just use the frontmater-entry here
Spelling fix.

```suggestion
// All of the check logic is exactly the same, so we can just use the frontmatter-entry here
```

2024-06-02 12:51 UTC, aji-ajani commented on themes/themes.typ
>  #import "./radial/radial.typ"
Not necessary, but we could have creator attributions in this file. Something like this:

```suggestion
/*
    Radial Theme
    Designed by @BattleCh1cken
    Implemented by @BattleCh1cken
*/
#import "./radial/radial.typ"
```

2024-06-02 12:51 UTC, aji-ajani commented on utils/components.typ
> +/// - callback (function): A function which returns the content of the toc. The function must take `frontmatter`, `body`, and `appendix` arguments.
Could we add an optional parameter to specify a page number from which to start including body entries into the TOC? This would allow for people to have TOC's for different sections of the notebook, which would be useful when splitting your notebook into multiple binders.

2024-06-02 12:51 UTC, aji-ajani commented on themes/default/components.typ
>    stack(..for entry in appendix {
Why doesn't this stack get 0.5em spacing like the stack for the body entries?

2024-06-02 12:51 UTC, aji-ajani commented on docs/src/reference.typ
> +  All of the examples show the default theme, other theme's components will look differently.
I think "other themes' components" is the most accurate grammatically.

2024-06-02 12:51 UTC, aji-ajani commented on themes/radial/components/gantt-chart.typ
> +/// - date-format (string): The way the date is formated using the `<datetime.display()>` method
Spelling fix.

```suggestion
/// - date-format (string): The way the date is formatted using the `<datetime.display()>` method
```

2024-06-02 12:51 UTC, aji-ajani commented on docs/src/developer_documentation/custom_themes.md
> +This syntax might look a little weird if you aren't familiar with functional programming. `make-pro-con` take a [`lambda`](https://typst.app/docs/reference/foundations/function/#unnamed) function as
Grammar fix.

```suggestion
This syntax might look a little weird if you aren't familiar with functional programming. `make-pro-con` takes a [`lambda`](https://typst.app/docs/reference/foundations/function/#unnamed) function as input, which is just a function without a name. This function takes two inputs: `pros` and `cons`, which are available inside the scope of the function like normal arguments would be on a named function.
```

2024-06-02 12:51 UTC, aji-ajani commented on docs/src/developer_documentation/custom_themes.md
>  For examples on how to create a pro / con table, check out out how [other themes](https://github.com/The-Notebookinator/notebookinator/tree/main/themes) implement them.
Grammar fix.

```suggestion
For examples on how to create a pro / con table, check out how [other themes](https://github.com/The-Notebookinator/notebookinator/tree/main/themes) implement them.
```

2024-06-02 12:51 UTC, aji-ajani commented on docs/src/developer_documentation/custom_themes.md
> +Using the constructor gives us access to three variables, `frontmatter`, `body`, and `appendix`. These variables are all [arrays](https://typst.app/docs/reference/foundations/array/), which dictionar
Agreed. Here is my suggestion to reword the sentence:


```suggestion
Using the constructor gives us access to three variables: `frontmatter`, `body`, and `appendix`. These variables are all [arrays](https://typst.app/docs/reference/foundations/array/), whose dictionaries all contain the same information as the `ctx` variables from [this](#creating-the-entries) section, with the addition of a `page-number` field, which is an [integer](https://typst.app/docs/reference/foundations/int/).
```

2024-06-02 12:51 UTC, aji-ajani commented on docs/src/developer_documentation/custom_themes.md
> +#let toc = utils.make-toc((_, body, appendix) => {
Agreed.

```suggestion
#let toc = utils.make-toc((_, body, appendix) => {
    // We replace the 'frontmatter' parameter with _ to indicate that we will not use it.
```

2024-06-02 12:51 UTC, aji-ajani commented on docs/src/developer_documentation/custom_themes.md
> +  // TODO: display the appendix entries as well
Is this comment meant for us or to tell the viewer to make their TOC also display appendix entries?

2024-06-02 12:51 UTC, aji-ajani commented on docs/src/developer_documentation/custom_themes.md
> +Inside of the function you have access to two variables, `properties`, and `data`. Properties contains a list of the properties the choices are being rated by, while `data` contains the scores for th
Clarity improvement.

```suggestion
Inside of the function you have access to two variables, `properties`, and `data`. Properties contains a list of the properties the choices are being rated by, while `data` contains the choices alongside the scores for those choices. You can run a [`repr()`](https://typst.app/docs/reference/foundations/repr/) on either of those variables to get a better understanding of how they're structured.
```

2024-06-05 17:44 UTC, BattleCh1cken commented on justfile
> +  set -euxo pipefail
I thought it would be more useful, but it hasn't really been.

2024-06-05 17:44 UTC, BattleCh1cken commented on lib.typ
>    show: doc => rules(doc)
https://typst.app/docs/reference/styling/#show-rules

2024-06-05 17:45 UTC, BattleCh1cken commented on lib.typ
> +    margin: 0pt,
They'd have to use a grid, or other formatting options like place. The cover API hasn't changed regardless.

2024-06-05 17:46 UTC, BattleCh1cken commented on utils/components.typ
> +      ctx.page-number = page-number
Themes will likely want to display the page number in the table of contents.

2024-06-05 17:47 UTC, BattleCh1cken commented on utils/components.typ
> +///   // ...
The usage is too complex, I covered it in the theme implementation guide.

2024-06-05 17:51 UTC, BattleCh1cken commented on docs/src/developer_documentation/custom_themes.md
> +  // TODO: display the appendix entries as well
Its meant for the viewer. @BestUsernamEver has a similar question, so I'll probably change that for clarity.

2024-06-06 23:35 UTC, BestUsernamEver commented on themes/themes.typ
>  #import "./radial/radial.typ"
I agree, especially since people will (hopefully) start contributing their own themes as the Notebookinator gets more popular.

2024-06-06 23:42 UTC, BestUsernamEver approved these changes

2024-06-07 00:16 UTC, BattleCh1cken commented on utils/components.typ
> +          message: "Property should be of type 'str'",
If the first param used the alternate format, but the second one didn't

2024-06-07 00:16 UTC, BattleCh1cken commented on utils/components.typ
> +///   Valid types include:
Can do

2024-06-07 20:15 UTC, BattleCh1cken commented on utils/theme.typ
> +  return doc => {
The entire document. I'll write the documentation for those functions in a moment.

2024-06-07 20:17 UTC, BattleCh1cken commented on themes/default/components.typ
>    stack(..for entry in appendix {
good question

2024-06-07 20:21 UTC, BattleCh1cken commented on utils/components.typ
> +/// - callback (function): A function which returns the content of the toc. The function must take `frontmatter`, `body`, and `appendix` arguments.
I'm not going to support this. Either manually split your pdf with some kind of pdf editor, or write multiple notebooks.

2024-06-07 20:26 UTC, BattleCh1cken commented on utils/components.typ
> +/// - callback (function): A function that returns the content for the pie chart. The function must take a `data` argument.
The constructor isn't just for standardizing paramaters, it also lets me check inputs. I plan to flesh this out farther in another pr adressing #33 .

2024-06-07 20:26 UTC, BattleCh1cken commented on utils/components.typ
> +// TODO: add method for these extra components:
Yes to both, updated the comment accordingly.

2024-06-07 20:26 UTC, BattleCh1cken commented on utils/theme.typ
> +    let valid-entry-types = (
No.

2024-06-07 20:27 UTC, BattleCh1cken commented on utils/theme.typ
> +        "author", // TODO: decide on the standard process for entry attribution
Sounds good I'll take a crack at implementing this tonight.

2024-06-11 20:19 UTC, BattleCh1cken commented on utils/theme.typ
> +        "author", // TODO: decide on the standard process for entry attribution
I think I might just add a `participants` argument (which is an array of strings) in addition to `author` and `witness`. This way themes can pick and choose which ones they want to use, and we don't create breaking changes in the user facing API.

2024-07-13 23:29 UTC, merged